//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/EYEAssets/_Input/BouncingBallInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BouncingBallInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BouncingBallInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BouncingBallInput"",
    ""maps"": [
        {
            ""name"": ""Ball"",
            ""id"": ""b33f405e-99b2-4567-ab91-09b8b5214843"",
            ""actions"": [
                {
                    ""name"": ""ChargedBounce"",
                    ""type"": ""Button"",
                    ""id"": ""4501e691-d141-4fdf-96a1-f9fee724351c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""421f88b7-b780-41b5-92b3-beed555d44ed"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold(duration=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChargedBounce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Ball
        m_Ball = asset.FindActionMap("Ball", throwIfNotFound: true);
        m_Ball_ChargedBounce = m_Ball.FindAction("ChargedBounce", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Ball
    private readonly InputActionMap m_Ball;
    private IBallActions m_BallActionsCallbackInterface;
    private readonly InputAction m_Ball_ChargedBounce;
    public struct BallActions
    {
        private @BouncingBallInput m_Wrapper;
        public BallActions(@BouncingBallInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ChargedBounce => m_Wrapper.m_Ball_ChargedBounce;
        public InputActionMap Get() { return m_Wrapper.m_Ball; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BallActions set) { return set.Get(); }
        public void SetCallbacks(IBallActions instance)
        {
            if (m_Wrapper.m_BallActionsCallbackInterface != null)
            {
                @ChargedBounce.started -= m_Wrapper.m_BallActionsCallbackInterface.OnChargedBounce;
                @ChargedBounce.performed -= m_Wrapper.m_BallActionsCallbackInterface.OnChargedBounce;
                @ChargedBounce.canceled -= m_Wrapper.m_BallActionsCallbackInterface.OnChargedBounce;
            }
            m_Wrapper.m_BallActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ChargedBounce.started += instance.OnChargedBounce;
                @ChargedBounce.performed += instance.OnChargedBounce;
                @ChargedBounce.canceled += instance.OnChargedBounce;
            }
        }
    }
    public BallActions @Ball => new BallActions(this);
    public interface IBallActions
    {
        void OnChargedBounce(InputAction.CallbackContext context);
    }
}
